USE LibraryApp;
DROP TABLE IF EXISTS Users;
CREATE TABLE Users (
	Username VARCHAR(30) PRIMARY KEY,
	Password VARCHAR(256) NOT NULL,
	IsAdmin BIT NOT NULL
);
INSERT INTO Users(Username,Password,IsAdmin) VALUES ('1','1',1);
INSERT INTO Users(Username,Password,IsAdmin) VALUES ('admin','admin',1);
INSERT INTO Users(Username,Password,IsAdmin) VALUES ('awilden0','dMHWcq',0);
INSERT INTO Users(Username,Password,IsAdmin) VALUES ('pvalentelli1','Y6SBIpwNAr7',0);
INSERT INTO Users(Username,Password,IsAdmin) VALUES ('bdunlap2','ELfyyYOJ',0);
INSERT INTO Users(Username,Password,IsAdmin) VALUES ('edunnett3','nVZmZy2',0);
INSERT INTO Users(Username,Password,IsAdmin) VALUES ('wweek4','9WQKux3LA',0);
INSERT INTO Users(Username,Password,IsAdmin) VALUES ('mtilberry5','KRwlf2yEg',0);
INSERT INTO Users(Username,Password,IsAdmin) VALUES ('tcummins6','5N6bOyDsd0',0);
INSERT INTO Users(Username,Password,IsAdmin) VALUES ('mgadd7','f4tFgo4QuZ',0);
INSERT INTO Users(Username,Password,IsAdmin) VALUES ('mgarvey8','MO8j7M',0);
INSERT INTO Users(Username,Password,IsAdmin) VALUES ('bchittem9','bq0Nsx',0);
INSERT INTO Users(Username,Password,IsAdmin) VALUES ('vzavittieria','OVrpPdM',0);
INSERT INTO Users(Username,Password,IsAdmin) VALUES ('rruxtonb','kj0IrNJFlT8',0);
INSERT INTO Users(Username,Password,IsAdmin) VALUES ('mstammerc','u3wV9R5BOK0',0);
INSERT INTO Users(Username,Password,IsAdmin) VALUES ('fplowsd','0pIEE59RRpJ4',0);
INSERT INTO Users(Username,Password,IsAdmin) VALUES ('cettelse','Z8p7Qyl05puK',0);
INSERT INTO Users(Username,Password,IsAdmin) VALUES ('mbickerstassef','26gaMeibh',0);
INSERT INTO Users(Username,Password,IsAdmin) VALUES ('mkearsleyg','M7cIAZ',0);
INSERT INTO Users(Username,Password,IsAdmin) VALUES ('zstrippelh','cwJBYzd2',0);
INSERT INTO Users(Username,Password,IsAdmin) VALUES ('fstaggei','4K6rdUic6',0);
INSERT INTO Users(Username,Password,IsAdmin) VALUES ('ojurekj','6ynNIZnwmu',0);
INSERT INTO Users(Username,Password,IsAdmin) VALUES ('kslopierk','AH3fmKR5Ei',0);
INSERT INTO Users(Username,Password,IsAdmin) VALUES ('npietrzykl','tQdCmAP',0);
INSERT INTO Users(Username,Password,IsAdmin) VALUES ('cmcevoym','yT16WbxH',0);
INSERT INTO Users(Username,Password,IsAdmin) VALUES ('jpotburyn','4dpdC2o',0);
INSERT INTO Users(Username,Password,IsAdmin) VALUES ('nkamenao','Narom2N6NKG',0);
INSERT INTO Users(Username,Password,IsAdmin) VALUES ('bgenesep','NvOzWW2IW',0);
INSERT INTO Users(Username,Password,IsAdmin) VALUES ('bgaskallq','19XMEQ29k',0);
INSERT INTO Users(Username,Password,IsAdmin) VALUES ('cklosr','A6cGFzxaGg',0);
INSERT INTO Users(Username,Password,IsAdmin) VALUES ('cblackmans','5ytdjbhALzJi',0);
INSERT INTO Users(Username,Password,IsAdmin) VALUES ('ppowlettt','XTk0r14f',0);
INSERT INTO Users(Username,Password,IsAdmin) VALUES ('lhallyboneu','s2fFrMOf8w',0);
INSERT INTO Users(Username,Password,IsAdmin) VALUES ('gstefanovicv','MxLgmJ',0);
INSERT INTO Users(Username,Password,IsAdmin) VALUES ('tsawnwyw','C763P2HOW',0);
INSERT INTO Users(Username,Password,IsAdmin) VALUES ('eflattx','zcZLC91Dd8',0);
INSERT INTO Users(Username,Password,IsAdmin) VALUES ('khedgey','FzLumLsk7n',0);
INSERT INTO Users(Username,Password,IsAdmin) VALUES ('mstoakesz','UgShlz',0);
INSERT INTO Users(Username,Password,IsAdmin) VALUES ('htimmins10','S23hyY6Z7R',0);
INSERT INTO Users(Username,Password,IsAdmin) VALUES ('apyford11','vNXEAj6A',0);
INSERT INTO Users(Username,Password,IsAdmin) VALUES ('ashitliff12','VkfsJvS967',0);
INSERT INTO Users(Username,Password,IsAdmin) VALUES ('adiggens13','5n9Ut5p',0);
INSERT INTO Users(Username,Password,IsAdmin) VALUES ('bronaldson14','dsOEHmz',0);
INSERT INTO Users(Username,Password,IsAdmin) VALUES ('bgerding15','TwHdH5iil1l',0);
INSERT INTO Users(Username,Password,IsAdmin) VALUES ('bgilkison16','MFjwePl1z1',0);
INSERT INTO Users(Username,Password,IsAdmin) VALUES ('nosmint17','3PZix7',0);
INSERT INTO Users(Username,Password,IsAdmin) VALUES ('slyes18','WSRrbGmdv',0);
INSERT INTO Users(Username,Password,IsAdmin) VALUES ('ktabb19','UXYJQM',0);
INSERT INTO Users(Username,Password,IsAdmin) VALUES ('jerrigo1a','tjGoSza',0);
INSERT INTO Users(Username,Password,IsAdmin) VALUES ('kwoodroofe1b','1a3vGFooyW',0);
INSERT INTO Users(Username,Password,IsAdmin) VALUES ('cmanilove1c','KX3bpzaz8eca',0);
INSERT INTO Users(Username,Password,IsAdmin) VALUES ('sborlease1d','xP5dLoPOuN',0);